name:                game
version:             0.1.0.0
license:             BSD3
author:              "biba"
copyright:           "2020 biba name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
 - base >= 4.7 && < 5
 - aeson
 - servant
 - servant-server
 - stm
 - mtl
 - servant-client
 - http-client

library:
  source-dirs: src

executables:
  game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game
    - warp
    
tests:
  game2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - hedgehog
